#!/usr/bin/python
import xml.etree.ElementTree as ET

# with open('String.Map.img.xml', 'r', encoding='utf-8') as file:
#     tree = ET.parse(file)

# 1. wzµ¼³öxml
tree = ET.parse('String.Map.img.xml')
root = tree.getroot()

outfile = open('outfile.txt', 'w', encoding='utf-8')
for child in root:
    # map, victoria
    # print(child.tag, child.attrib) 
    for child_map in child:
        map_node = child_map.attrib
        # print(map_node["name"])
        for map_info_node in child_map:
            # print(map_info_node.tag, map_info_node.attrib["name"], map_info_node.attrib["value"])
            if map_info_node.attrib["name"] == "mapName":
                outfile.write(map_node["name"] +" "+ map_info_node.attrib["value"])
                outfile.write('\n')
                print(map_node["name"], map_info_node.attrib["value"])